FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    fastapi==0.115.0 \
    uvicorn==0.30.0 \
    pandas==2.3.3 \
    numpy==2.1.3 \
    scikit-learn==1.5.2 \
    prometheus-client==0.21.0 \
    mlflow==2.19.0 \
    pydantic==2.9.0

COPY model_serving.py /app/model_serving.py

EXPOSE 8000

CMD ["uvicorn", "model_serving:app", "--host", "0.0.0.0", "--port", "8000"]
