FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    prometheus-client==0.21.0

COPY 3.prometheus_exporter.py /app/prometheus_exporter.py

EXPOSE 8001

CMD ["python", "prometheus_exporter.py"]
